<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>
    <ItemGroup>
        <PackageVersion Include="Avalonia" Version="12.1.3" />
        <PackageVersion Include="Avalonia.Desktop" Version="12.1.3" />
        <PackageVersion Include="Avalonia.Fonts.Inter" Version="12.1.3" />
        <PackageVersion Include="Avalonia.Headless.XUnit" Version="12.1.3" />
        <PackageVersion Include="Avalonia.Themes.Fluent" Version="12.1.3" />
        <PackageVersion Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3" />
        <PackageVersion Include="Fluid.Avalonia.Acrylic" Version="1.4.0" />
        <PackageVersion Include="Lucide.Avalonia" Version="0.2.24" />
        <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
        <PackageVersion Include="SukiUI.Motion" Version="7.0.2-nightly20261002.475" />
        <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
        <PackageVersion Include="xunit.v3" Version="3.2.2" />
    </ItemGroup>
</Project>
